### ISSUE TITLE
LGraphCanvas.enableWebGL in a TS (+npm) environment

### ISSUE THREAD

**Issue by altarfinch** [jagenjo/litegraph.js#140]
Does someone knows how to make LGraphCanvas.enableWebGL work in a TS (+npm) environment ?
Can't find a way to include these dependencies: Canvas2DtoWebGL, gl-matrix-min, litegl.
No matter what I tried, enableWebGLCanvas is never globally defined.

**Comment by altarfinch** [comment]
It's fixed, these files had some undeclared variable:
src/nodes/gltextures.js
src/nodes/glfx.js

And there is a wrong definition in:
src/litegraph.d.ts

https://github.com/altarfinch/litegraph.js/commit/93ba405a23a412ea361becd4503f00caf44a890d

**Comment by jagenjo** [comment]
the webgl feature in litegraph is a little bit experimental, Im using it in webglstudio.org (which was the reason why I created litegraph in the first place) but because I test it always inside webglstudio sometimes code that asumes you are in webglstudio could leak to litegraph, so I added the function to visualize a webgl window on litegraph demo, but I wouldnt recommend to use at the current stage.

**Comment by altarfinch** [comment]
Maybe is it working in webglstudio because there is no "use strict" in litegraph.js.
Initially I was merging some three.js content using ctx.putImageData, but the render loop was not in sync with the canvas drawing. I'll try the WebGL mode and revert if it's too much troubles.
Thanks.
