### ISSUE TITLE
Documents: Require documents to understand different nodes

### ISSUE THREAD

**Issue by AztrexDX** [jagenjo/litegraph.js#258]
Hi,

I understand basic nodes but nodes like canvas, I am not able to understand within litegraph. Like there is canvas node where does it draw image?

Is there any proper document for nodes or api

**Comment by atlasan** [comment]
The canvas node gives you a canvas "variable", with that you can draw it using a "frame" node. You have to draw something inside the canvas to see a result in the frame. There are the "drawimage" node (use an "image" node with an url) and the "drawrectangle" node, with those you can try the canvas, these are examples of how to implement such functionalities, you can write your nodes to do more.

**Comment by jagenjo** [comment]
The problem is that most nodes are more a Proof of Concept of what can be done using LiteGraph, than a real useful node.

For instance the ones related to Canvas I did them almost 10 years ago so they are very deprecated, I just didnt want to remove them as a showcase of nodes centered around the canvas.

The same happends with the audio ones.

It would be nice to use the WIki on Github to describe every node and also rework some of them, but I guess the idea of LiteGraph is more to encourage people to create their own nodes repository.

**Comment by AztrexDX** [comment]
Thanks for explanation
