### ISSUE TITLE
Add Types

### ISSUE THREAD

**Issue by gotwig** [jagenjo/litegraph.js#31]
Right now we have categories, but I think types are missing.

Types can be defined at creating nodes and could be used to better destinguish how to represent them visualy in the following ways (similar to unreal engine 4 blueprints):

Better context approach
Nodes that act as "Variables"
Types can have icons, those appear left to node name
Different context colors, if you work with events, functions, variables, widgets or something other

Example:
https://blueprintue.com/blueprint/_dqx9spf/

Events are red, variables have their own styling, functions are clearly visible as functions.

**Comment by jagenjo** [comment]
You can achieve most of those things already, nodes can define their colors (background, foreground, and little box) and also the shape, so you can create a node type with some special way of rendering it.

About icons, I will consider adding it but because I never have time to design icons is going to be an unused feature.

**Comment by gotwig** [comment]
i know that this is easy to realize because its basicly just another property but i thought it would make sense to have this option in upstream and demo :)

**Comment by jagenjo** [comment]
but you already have it! in those nodes that you feel should be different, define the colors and shape in its constructor
