### ISSUE TITLE
good way to create a list of objects

### ISSUE THREAD

**Issue by RiccardoRossi** [jagenjo/litegraph.js#85]
Hello,
       i wanted to ask what is the best way to create a list of objects.

so far i am creating an empty list and pushing it back to it as shown in the picture ... but it is a little verbose. Any better way of achieving it?

thanks in advance for any help. (and compliments, the lib is very well structured!)

![Screenshot from 2019-10-17 09-25-51](https://user-images.githubusercontent.com/8059665/66987160-7e9b3a00-f0c0-11e9-98a7-7ad81ff019fe.png)

**Comment by jagenjo** [comment]
I always recommend to create your own nodes to fill your necessities, because the base pool of nodes has been developed with a very specific purpose in mind that do not usually fit everybody's pipeline.

Check the optional callback onGetInputs/onGetOutputs for nodes, it allows you to add a variable number of inputs/outputs.

Also you can add a button widget to add more inputs to a node.
